basePath: /api
definitions:
  dto.AddVehicle:
    properties:
      brand:
        type: string
      color:
        type: string
      license_plate:
        maxLength: 10
        minLength: 3
        type: string
      model:
        type: string
      year:
        maxLength: 5
        minLength: 4
        type: string
    required:
    - brand
    - color
    - license_plate
    - model
    - year
    type: object
  dto.Login:
    properties:
      email:
        type: string
      password:
        maxLength: 64
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  dto.UpdateVehicle:
    properties:
      brand:
        type: string
      color:
        type: string
      license_plate:
        maxLength: 10
        minLength: 3
        type: string
      model:
        type: string
      year:
        maxLength: 5
        minLength: 4
        type: string
    type: object
  dto.UserRegister:
    properties:
      email:
        type: string
      name:
        maxLength: 100
        minLength: 3
        type: string
      password:
        maxLength: 64
        minLength: 8
        type: string
      phone:
        maxLength: 15
        minLength: 9
        type: string
    required:
    - email
    - name
    - password
    - phone
    type: object
  dto.UserUpdate:
    properties:
      email:
        type: string
      name:
        maxLength: 100
        minLength: 3
        type: string
      password:
        maxLength: 64
        minLength: 8
        type: string
      phone:
        maxLength: 15
        minLength: 9
        type: string
    type: object
  response.Error:
    properties:
      code:
        type: integer
      data: {}
      error: {}
      log_id:
        type: string
      message:
        type: string
      status:
        type: boolean
    type: object
  response.Success:
    properties:
      code:
        type: integer
      data: {}
      error: {}
      log_id:
        type: string
      message:
        type: string
      status:
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: zaiduszhuhur@gmail.com
    name: API Support
    url: https://www.linkedin.com/in/zaidus-zhuhur/
  description: This is a sample server for a workshop management service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Workshop Management API
  version: "1.0"
paths:
  /user:
    delete:
      consumes:
      - application/json
      description: Delete a user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - ApiKeyAuth: []
      summary: Delete a user
      tags:
      - Users
    get:
      consumes:
      - application/json
      description: Get a user by JWT token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - ApiKeyAuth: []
      summary: Get a user by JWT token
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: Update a user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User update details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UserUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - ApiKeyAuth: []
      summary: Update a user
      tags:
      - Users
  /user/{id}:
    get:
      consumes:
      - application/json
      description: Get a user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - ApiKeyAuth: []
      summary: Get a user by ID
      tags:
      - Users
  /user/login:
    post:
      consumes:
      - application/json
      description: Login a user
      parameters:
      - description: User login details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Login a user
      tags:
      - Users
  /user/logout:
    post:
      consumes:
      - application/json
      description: Logout a user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - ApiKeyAuth: []
      summary: Logout a user
      tags:
      - Users
  /user/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User registration details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.UserRegister'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Register a new user
      tags:
      - Users
  /users:
    get:
      consumes:
      - application/json
      description: Get all users
      parameters:
      - description: Page number for pagination
        in: query
        name: page
        type: integer
      - description: Number of items per page
        in: query
        name: limit
        type: integer
      - description: Field to sort by
        in: query
        name: order_by
        type: string
      - description: Sort direction (asc/desc)
        in: query
        name: order_direction
        type: string
      - description: Search query to filter vehicles
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - ApiKeyAuth: []
      summary: Get all users
      tags:
      - Users
  /vehicle:
    post:
      consumes:
      - application/json
      description: Create a new vehicle with the provided details.
      parameters:
      - description: Vehicle details to be created
        in: body
        name: vehicle
        required: true
        schema:
          $ref: '#/definitions/dto.AddVehicle'
      produces:
      - application/json
      responses:
        "201":
          description: Vehicle created successfully
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - ApiKeyAuth: []
      summary: Create a new vehicle
      tags:
      - Vehicles
  /vehicle/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a vehicle by its ID.
      parameters:
      - description: Vehicle ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Vehicle deleted successfully
          schema:
            $ref: '#/definitions/response.Success'
        "404":
          description: Vehicle not found
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - ApiKeyAuth: []
      summary: Delete a vehicle
      tags:
      - Vehicles
    get:
      consumes:
      - application/json
      description: Retrieve vehicle details using the vehicle ID.
      parameters:
      - description: Vehicle ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Vehicle details retrieved successfully
          schema:
            $ref: '#/definitions/response.Success'
        "404":
          description: Vehicle not found
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - ApiKeyAuth: []
      summary: Get a vehicle by ID
      tags:
      - Vehicles
    put:
      consumes:
      - application/json
      description: Update an existing vehicle's details.
      parameters:
      - description: Vehicle ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated vehicle details
        in: body
        name: vehicle
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateVehicle'
      produces:
      - application/json
      responses:
        "200":
          description: Vehicle updated successfully
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/response.Error'
        "404":
          description: Vehicle not found
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - ApiKeyAuth: []
      summary: Update a vehicle
      tags:
      - Vehicles
  /vehicle/list:
    get:
      consumes:
      - application/json
      description: Retrieve a list of vehicles with optional filters and pagination.
      parameters:
      - description: Page number for pagination
        in: query
        name: page
        type: integer
      - description: Number of items per page
        in: query
        name: limit
        type: integer
      - description: Field to sort by
        in: query
        name: order_by
        type: string
      - description: Sort direction (asc/desc)
        in: query
        name: order_direction
        type: string
      - description: Search query to filter vehicles
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of vehicles retrieved successfully
          schema:
            $ref: '#/definitions/response.Success'
        "404":
          description: No vehicles found
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - ApiKeyAuth: []
      summary: Get a list of vehicles
      tags:
      - Vehicles
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
